config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'contacts#index', as: :root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end


  resources :contacts, except: [:show]
  resources :groups, except: [:show]
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :groups

  validates_presence_of :first_name, :last_name, :phone, :email
  validates_format_of :email, with: Devise::email_regexp

  validates :phone, phony_plausible: true
  phony_normalize :phone, default_country_code: 'US'

  mount_uploader :image, ImageUploader


  def name
    "#{first_name} #{last_name}".titleize
  end
end

app/models/contacts_group.rb
class ContactsGroup < ActiveRecord::Base
  belongs_to :contact
  belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user

  has_many :contacts_groups
  has_and_belongs_to_many :contacts


  accepts_nested_attributes_for :contacts_groups, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contacts
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!


  def index

    respond_to do |format|
      format.html do
        @contacts = current_user.contacts
        @contact = current_user.contacts.build
      end

      format.json do
        render json: ContactsDatatable.new(view_context)
      end
    end
  end


  def create
    @contact = current_user.contacts.create(contact_params)

    if @contact.errors.any?
      @contacts = current_user.contacts
      render :index

    else
      redirect_to :back, flash: {success: 'Contact created!'}
    end
  end


  def edit
    @contact = current_user.contacts.find params[:id]
  end


  def update
    @contact = current_user.contacts.find params[:id]

    @contact.update contact_params

    if @contact.errors.any?
      render :edit

    else
      redirect_to :back, flash: {success: 'Contact updated!'}
    end
  end


  def destroy
    contact = current_user.contacts.find params[:id]
    contact.destroy!

    redirect_to :back, flash: {success: 'Contact deleted!'}
  end

private
  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :phone, :company, :image)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!


  def index
    @groups = current_user.groups.includes(:contacts)
    @group = @groups.build
  end


  def create
    current_user.groups.create!(group_params)

    redirect_to :back, flash: {success: 'Group created!'}
  end


  def edit
    @group = current_user.groups.find params[:id]
    @contacts = current_user.contacts.to_a
    @group_contacts = @group.contacts_groups.includes(:contact).to_a

    @contacts -= @group.contacts.to_a
  end


  def update
    return redirect_to(:back, flash: {info: 'Nothing to update!'}) if params[:group].blank?

    @group = current_user.groups.find params[:id]

    @group.update! group_params

    redirect_to :back, flash: {success: 'Group updated!'}
  end


  def destroy
    group = current_user.groups.find params[:id]

    group.destroy!

    redirect_to :back, flash: {success: 'Group deleted!'}
  end


private
  def group_params
    params.require(:group).permit(:name, contacts_groups_attributes: [:id, :contact_id, :group_id, :_destroy])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_contact_actions.html.haml
= link_to edit_contact_path(contact), class: 'btn btn-xs btn-info', title: 'Edit' do
  %i.fa.fa-edit

= link_to contact_path(contact), method: :delete, class: 'btn btn-xs btn-danger', |
    title: 'Delete', data: {confirm: 'Are you sure?'} do
  %i.fa.fa-trash-o

app/views/contacts/_contact_groups.html.haml
- links = contact.groups.map {|group| link_to group.name, edit_group_path(group)}

= links.join(', ').html_safe

app/views/contacts/_form.html.haml
= form_for contact, class: 'form' do |f|
  - if contact.errors.any?
    #error_explanation
      %h2
        = pluralize(contact.errors.count, 'error')
        prohibited this contact from being saved:

      %ul
        - contact.errors.full_messages.each do |msg|
          %li= msg

  .col-md-6
    .field
      .form-group.col-md-4
        = f.label :first_name, 'First name *'
      .form-group.col-md-6
        = f.text_field :first_name, class: 'form-control', required: true

    .field
      .form-group.col-md-4
        = f.label :last_name, 'Last name *'
      .form-group.col-md-6
        = f.text_field :last_name, class: 'form-control', required: true

    .field
      .form-group.col-md-4
        = f.label :email, 'Email *'
      .form-group.col-md-6
        = f.text_field :email, class: 'form-control', required: true

  .col-md-6
    .field
      .form-group.col-md-4
        = f.label :phone, 'Phone *'
      .form-group.col-md-6
        = f.text_field :phone, class: 'form-control', required: true


    .field
      .form-group.col-md-4
        = f.label :company
      .form-group.col-md-6
        = f.text_field :company, class: 'form-control'


    .field
      .form-group.col-md-4
        = f.label :image
      .form-group.col-md-6
        = f.file_field :image,  accept: '.gif, .jpeg, .jpg, .png', class: 'form-control'

  - if contact.id.present?
    .col-md-6
      .field
        .form-group.col-md-4
          = label_tag do
            Current Image

        .form-group.col-md-6
          - if contact.image.present?
            .img-thumb{style: "background-image: url(#{contact.image_url})"}

          - else
            .img-thumb
              %i.fa.fa-2x.fa-user

  .field
    %em.text-muted Fields marked with * are required

  .field
    = f.submit class: 'btn btn-md btn-primary'

app/views/contacts/edit.html.haml
.col-md-12
  .well.col-md-12
    %h3 Edit Contact

    = render partial: 'contacts/form', locals: {contact: @contact}

app/views/contacts/index.html.haml
%h3 My Contacts

.col-md-12
  %table.table.table-striped#contacts{data: {src: contacts_path}}
    %thead.bg-primary
      %tr
        %th First Name
        %th Last Name
        %th Email
        %th Phone
        %th Company
        %th Groups
        %th Actions


%hr.col-md-12

.col-md-12
  .well.col-md-12
    %h3 Add Contact

    = render partial: 'contacts/form', locals: {contact: @contact}

app/views/groups/_form.html.haml
= form_for group, class: 'form' do |f|
  .field
    .form-group.col-md-4
      = f.label :name
    .form-group.col-md-6
      = f.text_field :name, class: 'form-control', required: true


  .field
    = f.submit class: 'btn btn-sm btn-primary'

app/views/groups/edit.html.haml
.col-md-12.well
  %h3
    Edit group:
    = @group.name

  = render partial: 'groups/form', locals: {group: @group}


.col-md-6
  .well.col-md-12
    %h3 Current contacts in group

    = form_for @group, class: 'form' do |f|
      - if @group_contacts.size == 0
        %p.text-muted No contacts are available to be removed

      - @group_contacts.each do |group_contact|
        - contact = group_contact.contact
        .col-md-6
          .img-thumb{style: "background-image: url(#{contact.image_url});"}
          = contact.name
          .checkbox
            = hidden_field_tag 'group[contacts_groups_attributes][][id]', group_contact.id

            = label_tag nil do
              = check_box_tag 'group[contacts_groups_attributes][][_destroy]', true
              Remove

      .field
        %br
        = f.submit 'Remove selected', class: 'btn btn-sm btn-primary'


.col-md-6
  .well.col-md-12
    %h3 Add contacts in group

    = form_for @group, class: 'form' do |f|
      - if @contacts.size == 0
        %p.text-muted No contacts are available to be added

      - @contacts.each do |contact|
        .col-md-6
          .img-thumb{style: "background-image: url(#{contact.image_url});"}
          = contact.name
          .checkbox
            = label_tag nil do
              = check_box_tag 'group[contacts_groups_attributes][][contact_id]', contact.id
              Add

      .field
        %br
        = f.submit 'Add selected', class: 'btn btn-sm btn-primary'

app/views/groups/index.html.haml
%table.table.table-striped
  %thead.bg-primary
    %tr
      %td Group Name
      %td Members
      %td Actions

  %tbody
    - @groups.each do |group|
      - next if group.id.blank?

      %tr
        %td= group.name

        %td
          = group.contacts.map {|contact| contact.name}.join(', ')

        %td
          = link_to edit_group_path(group), class: 'btn btn-xs btn-info' do
            %i.fa.fa-edit

          = link_to group_path(group), class: 'btn btn-xs btn-danger', |
              method: :delete, data: {confirm: 'Are you sure?'} do

            %i.fa.fa-trash-o


%hr.col-md-12


.col-md-5.well
  %h4 Create group

  = render partial: 'groups/form', locals: {group: @group}

app/views/layouts/application.html.haml
!!! 5
%html{lang: 'en'}
  %head
    %meta{charset: 'utf-8'}
    %meta{'http-equiv'=> 'X-UA-Compatible', content: 'IE=Edge,chrome=1'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}

    %title
      = content_for?(:title) ? yield(:title) : 'ContactsApp'

    = csrf_meta_tags

    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js'

    = stylesheet_link_tag 'application', media: 'all'
    = favicon_link_tag 'favicon.ico', rel: 'shortcut icon'
    = javascript_include_tag 'application'


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle{type: 'button', data: {toggle: 'collapse', target: '.navbar-responsive-collapse'}}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand{href: '#'} ContactsApp

        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li
              = link_to 'Home', '#'

    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

      %footer.text-center
        .col-lg-12
          %hr
        %p &copy; ContactsApp 2015

app/views/layouts/devise.html.haml
!!!5
%html{lang: 'en'}
  = render partial: 'layouts/partials/head'

  %body
    = render partial: 'layouts/partials/navbar'

    .container
      .row
        .col-lg-12
          = bootstrap_flash

      .row
        .col-md-6.col-md-offset-3.well.text-center
          = yield

      = render partial: 'layouts/partials/footer'

app/views/layouts/partials/_footer.html.haml
%footer.text-center
  .col-lg-12
    %hr
  %p &copy; ContactsApp 2015

app/views/layouts/partials/_head.html.haml
%head
  %meta{charset: 'utf-8'}
  %meta{'http-equiv'=> 'X-UA-Compatible', content: 'IE=Edge,chrome=1'}
  %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}

  %title
    = content_for?(:title) ? yield(:title) : 'ContactsApp'

  = csrf_meta_tags

  / Le HTML5 shim, for IE6-8 support of HTML elements
  /[if lt IE 9]
    = javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js'

  = stylesheet_link_tag 'application', media: 'all'
  = favicon_link_tag 'favicon.ico', rel: 'shortcut icon'
  = javascript_include_tag 'application'

app/views/layouts/partials/_navbar.html.haml
.navbar.navbar-default.navbar-static-top
  .container
    %button.navbar-toggle{type: 'button', data: {toggle: 'collapse', target: '.navbar-responsive-collapse'}}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{href: root_path} ContactsApp

    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav
        - if user_signed_in?
          %li
            = link_to 'Contacts', root_path

          %li
            = link_to 'Groups', groups_path

      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.active
            = link_to current_user.email, edit_user_registration_path

          %li
            = link_to 'Sign out', destroy_session_path(current_user), method: :delete